# netlify.toml

# Global settings applied to the whole site.
[build]
  # (optional) Settings for the build command and output directory.
  # Adjust these if you have specific build requirements.
  # command = "npm run build"
  # publish = "dist"

# Redirect and rewrite rules
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# Headers to return with requests for the specified paths
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*.js"
    [headers.values]
    Content-Type = "application/javascript"

# (optional) Advanced settings to optimize your site
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true